name: 'Automated Release: Run ORYX download, macro enhancement post-processor & QMK compiler'

on:
  push:
  workflow_dispatch:

jobs:
  process_macros:
    runs-on: ubuntu-latest
    name: Macro Enhancement
    env:
      LAYOUT_ID: ${{ vars.LAYOUT_ID }}
      LAYOUT_FOLDER: ${{ vars.LAYOUT_FOLDER }}
      USER_NAME: ${{ github.event.repository.owner.name }}
    steps:
      - uses: actions/checkout@v3
      - name: Dump github context
        run: echo "$GITHUB_CONTEXT"
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install
        run: npm install
      - name: Get ORYX layout
        run: npm run get
      - name: Process macros
        run: npm start
      - name: Compile QMK Firmware from source
        uses: Phoscur/QMK-compile@main
        with:
          path: layout_src/${{ vars.LAYOUT_FOLDER }}
          artifacts_path: ${{ github.workspace }}/artifacts
          keymap: firmware
          keyboard: moonlander
      - uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: 'latest'
          title: 'Updated firmware'
          files: |
            artifacts/moonlander_firmware.bin
